// <auto-generated />
using System;
using Athena.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Athena.Infrastructure.Migrations
{
    [DbContext(typeof(AthenaDbContext))]
    [Migration("20260115141853_MigratingKeyToGuid")]
    partial class MigratingKeyToGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Athena.Domain.Entities.ToDo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeadLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Finished")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Important")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ToDo_ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToDo_ParentId");

                    b.ToTable("ToDo");
                });

            modelBuilder.Entity("Athena.Domain.Entities.ToDo", b =>
                {
                    b.HasOne("Athena.Domain.Entities.ToDo", "ParentToDo")
                        .WithMany("ToDos")
                        .HasForeignKey("ToDo_ParentId");

                    b.Navigation("ParentToDo");
                });

            modelBuilder.Entity("Athena.Domain.Entities.ToDo", b =>
                {
                    b.Navigation("ToDos");
                });
#pragma warning restore 612, 618
        }
    }
}
