FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build-env
WORKDIR /app
COPY ./Athena.Presentation/*.csproj ./Athena.Presentation/
COPY ./Athena.Application/*.csproj ./Athena.Application/
COPY ./Athena.Domain/*.csproj ./Athena.Domain/
COPY ./Athena.Infrastructure/*.csproj ./Athena.Infrastructure/
COPY ./Athena.IoC/*.csproj ./Athena.IoC/

RUN dotnet restore Athena.Presentation

COPY . ./

RUN dotnet publish Athena.Presentation -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base-env
WORKDIR /app
COPY --from=build-env /app/out .

EXPOSE 8080
ENTRYPOINT [ "dotnet", "Athena.Presentation.dll" ]